Maven-archetype for siddhi-testsuite
wso2-extensions/siddhi-maven-archetype pull request #23
Opened 2020-01-13 06:57 UTC by PrabodDunuwila

## Purpose
> $subject

## Goals
> Generate siddhi-testsuite project using siddhi-maven-archetype.

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

2020-01-13 07:24 UTC, pcnfernando requested changes

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/pom.xml
> +                                <!--Jars to be included for AppTest.-->
Add more descriptive comment

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/pom.xml
> +                                <!--Jars to be included for AppTest.-->
Say why you are bundling defaults

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/main/java/sample/containers/LoggerServiceContainer.java
> +package sample.containers;
License missing

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/main/java/sample/containers/LoggerServiceContainer.java
> + * Siddhi Logger Service container class. This is a sample LoggerServiceContainer which can be used to log a message.
Rephrase the comments.

Sample container extending the Container framework which logs events received through an HTTP endpoint.

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/main/java/sample/containers/LoggerServiceContainer.java
> +    private static final String IMAGE_NAME = "siddhi-logservice";
You have added a image built locally. Clean the image and push it to siddhiio docker repo

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/main/java/sample/containers/LoggerServiceContainer.java
> +    private HTTPClient.HTTPResponseMessage callHealthAPI() {
This method is never used

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/AbstractTemperatureAlertTests.java
> +package sample;
License missing

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/AbstractTemperatureAlertTests.java
> + * Class for AbstractTemperatureAlertTests of Temp-Alert-App. This class includes the common logic for integration
Rephrase as Abstract tests for Temp-Alert-App. This class includes the common logic for integration tests and blackbox tests.

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/AbstractTemperatureAlertTests.java
> +    public abstract void setUpCluster() throws IOException, InterruptedException;
Add comments

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/AbstractTemperatureAlertTests.java
> +    public MySQLContainer mySQLContainer;
Why these containers are in Abstract class. These are only used in Integration tests?

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/AbstractTemperatureAlertTests.java
> +            siddhiLogConsumer.waitUntil(frame ->
You cannot assert from logConsumer for Blackbox teste right? Update the Temperature app to publish the result to the log service and assert from there

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/blackbox/BlackBoxTestsOfTemperatureApp.java
> +package sample.blackbox;
license missing

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/blackbox/BlackBoxTestsOfTemperatureApp.java
> + * Class for black box testing of Temp-Alert-App. Run black-box testing by configuring the Siddhi Runner instances
Rephrase class comments as in integration tests

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/blackbox/BlackBoxTestsOfTemperatureApp.java
> +    //Provide configurations for Nats and mysql environments.
Rephrase the comment as **Update the Nats and MySql configurations as per your environment for Siddhi test framework to communicate with the said instances**

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/blackbox/BlackBoxTestsOfTemperatureApp.java
> +        siddhiRunnerContainer = new SiddhiRunnerContainer("siddhiio/siddhi-runner-alpine:latest-dev")
Is it possible to get the Siddhi Runner image name and version during interactive mode and update the classes accordingly. Use **siddhiio/siddhi-runner-alpine:latest-dev** as defaults

2020-01-13 07:24 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/sample/unit/UnitTestsOfTemperatureApp.java
> +        envMap.put("CLUSTER_ID", "");
Check whether without setting the envs to ""; works?

2020-01-13 07:30 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/resources/testng.xml
> +            <class name="sample.blackbox.BlackBoxTestsOfTemperatureApp"/>
You cannot run Blackbox tests without user configuring the URLs. Comment the said class from testng and say steps to enable

2020-01-13 07:33 UTC, niveathika commented on README.md
> +    | classNameOfBlackBoxTest | Class name of the BlackBoxTest | N | BlackBoxTestsOf{_nameOfTestsuite}
Better if we change the names of the classes to, `{_nameOfTestsuite}UnitTestCase`, similar changes to the rest...

2020-01-16 11:38 UTC, pcnfernando commented on siddhi-testsuite/src/main/resources/archetype-resources/component/src/test/java/template/unit/__classNameOfUnitTest__.java
> +    @BeforeClass
Add comments to all empty bodies in the template

2020-01-17 06:13 UTC, pcnfernando approved these changes

2020-01-17 06:13 UTC, merged